### ISSUE TITLE
A response body with no example causes crash

### ISSUE THREAD

**Issue by dcrossleyau** [janrain/raml-fleece#44]
Some RAML examples do not provide an "example" or "schema" for a response body.

When raml-fleece encounters this, it just crashes with:

TypeError: Cannot read property 'example' of null
    at /opt/local/lib/node_modules/raml-fleece/src/main.js:106:19
    at /opt/local/lib/node_modules/raml-fleece/node_modules/lodash/lodash.js:3579:27
    ...

**Comment by dcrossleyau** [comment]
I did omit a test document. Now attached:
[plain-with-example.raml.txt](https://github.com/janrain/raml-fleece/files/820018/plain-with-example.raml.txt)
[plain-with-no-example.raml.txt](https://github.com/janrain/raml-fleece/files/820019/plain-with-no-example.raml.txt)
